// Скрипт для добавления upgrade данных для Plush Pepe
// Запуск: mongosh "mongodb://127.0.0.1:27017/telegram" scripts/add_plush_pepe_upgrade.js

const BASE_MODEL = "https://cdn.changes.tg/gifts/models/Plush%20Pepe/lottie/";
const BASE_PATTERN = "https://cdn.changes.tg/gifts/patterns/Plush%20Pepe/lottie/";

const models = [
  {name: "Amalgam", animationType: "lottie", animationUrl: BASE_MODEL + "Amalgam.json", rarityPermille: 20},
  {name: "Aqua Plush", animationType: "lottie", animationUrl: BASE_MODEL + "Aqua%20Plush.json", rarityPermille: 20},
  {name: "Barcelona", animationType: "lottie", animationUrl: BASE_MODEL + "Barcelona.json", rarityPermille: 20},
  {name: "Bavaria", animationType: "lottie", animationUrl: BASE_MODEL + "Bavaria.json", rarityPermille: 20},
  {name: "Birmingham", animationType: "lottie", animationUrl: BASE_MODEL + "Birmingham.json", rarityPermille: 20},
  {name: "Christmas", animationType: "lottie", animationUrl: BASE_MODEL + "Christmas.json", rarityPermille: 20},
  {name: "Cold Heart", animationType: "lottie", animationUrl: BASE_MODEL + "Cold%20Heart.json", rarityPermille: 20},
  {name: "Cozy Galaxy", animationType: "lottie", animationUrl: BASE_MODEL + "Cozy%20Galaxy.json", rarityPermille: 20},
  {name: "Donatello", animationType: "lottie", animationUrl: BASE_MODEL + "Donatello.json", rarityPermille: 20},
  {name: "Eggplant", animationType: "lottie", animationUrl: BASE_MODEL + "Eggplant.json", rarityPermille: 20},
  {name: "Emerald Plush", animationType: "lottie", animationUrl: BASE_MODEL + "Emerald%20Plush.json", rarityPermille: 20},
  {name: "Emo Boi", animationType: "lottie", animationUrl: BASE_MODEL + "Emo%20Boi.json", rarityPermille: 20},
  {name: "Fifty Shades", animationType: "lottie", animationUrl: BASE_MODEL + "Fifty%20Shades.json", rarityPermille: 20},
  {name: "Frozen", animationType: "lottie", animationUrl: BASE_MODEL + "Frozen.json", rarityPermille: 20},
  {name: "Gucci Leap", animationType: "lottie", animationUrl: BASE_MODEL + "Gucci%20Leap.json", rarityPermille: 20},
  {name: "Gummy Frog", animationType: "lottie", animationUrl: BASE_MODEL + "Gummy%20Frog.json", rarityPermille: 20},
  {name: "Hothead", animationType: "lottie", animationUrl: BASE_MODEL + "Hothead.json", rarityPermille: 20},
  {name: "Hue Jester", animationType: "lottie", animationUrl: BASE_MODEL + "Hue%20Jester.json", rarityPermille: 20},
  {name: "Kung Fu Pepe", animationType: "lottie", animationUrl: BASE_MODEL + "Kung%20Fu%20Pepe.json", rarityPermille: 20},
  {name: "Leonardo", animationType: "lottie", animationUrl: BASE_MODEL + "Leonardo.json", rarityPermille: 20},
  {name: "Louis Vuittoad", animationType: "lottie", animationUrl: BASE_MODEL + "Louis%20Vuittoad.json", rarityPermille: 20},
  {name: "Magnate", animationType: "lottie", animationUrl: BASE_MODEL + "Magnate.json", rarityPermille: 20},
  {name: "Marble", animationType: "lottie", animationUrl: BASE_MODEL + "Marble.json", rarityPermille: 20},
  {name: "Midas Pepe", animationType: "lottie", animationUrl: BASE_MODEL + "Midas%20Pepe.json", rarityPermille: 20},
  {name: "Milano", animationType: "lottie", animationUrl: BASE_MODEL + "Milano.json", rarityPermille: 20},
  {name: "Ninja Mike", animationType: "lottie", animationUrl: BASE_MODEL + "Ninja%20Mike.json", rarityPermille: 20},
  {name: "Original", animationType: "lottie", animationUrl: BASE_MODEL + "Original.json", rarityPermille: 20},
  {name: "Pepe La Rana", animationType: "lottie", animationUrl: BASE_MODEL + "Pepe%20La%20Rana.json", rarityPermille: 20},
  {name: "Pepemint", animationType: "lottie", animationUrl: BASE_MODEL + "Pepemint.json", rarityPermille: 20},
  {name: "Pink Galaxy", animationType: "lottie", animationUrl: BASE_MODEL + "Pink%20Galaxy.json", rarityPermille: 20},
  {name: "Pink Latex", animationType: "lottie", animationUrl: BASE_MODEL + "Pink%20Latex.json", rarityPermille: 20},
  {name: "Poison Dart", animationType: "lottie", animationUrl: BASE_MODEL + "Poison%20Dart.json", rarityPermille: 20},
  {name: "Polka Dots", animationType: "lottie", animationUrl: BASE_MODEL + "Polka%20Dots.json", rarityPermille: 20},
  {name: "Princess", animationType: "lottie", animationUrl: BASE_MODEL + "Princess.json", rarityPermille: 20},
  {name: "Pumpkin", animationType: "lottie", animationUrl: BASE_MODEL + "Pumpkin.json", rarityPermille: 20},
  {name: "Puppy Pug", animationType: "lottie", animationUrl: BASE_MODEL + "Puppy%20Pug.json", rarityPermille: 20},
  {name: "Raphael", animationType: "lottie", animationUrl: BASE_MODEL + "Raphael.json", rarityPermille: 20},
  {name: "Red Menace", animationType: "lottie", animationUrl: BASE_MODEL + "Red%20Menace.json", rarityPermille: 20},
  {name: "Red Pepple", animationType: "lottie", animationUrl: BASE_MODEL + "Red%20Pepple.json", rarityPermille: 20},
  {name: "Santa Pepe", animationType: "lottie", animationUrl: BASE_MODEL + "Santa%20Pepe.json", rarityPermille: 20},
  {name: "Sketchy", animationType: "lottie", animationUrl: BASE_MODEL + "Sketchy.json", rarityPermille: 20},
  {name: "Spectrum", animationType: "lottie", animationUrl: BASE_MODEL + "Spectrum.json", rarityPermille: 20},
  {name: "Steel Frog", animationType: "lottie", animationUrl: BASE_MODEL + "Steel%20Frog.json", rarityPermille: 20},
  {name: "Stripes", animationType: "lottie", animationUrl: BASE_MODEL + "Stripes.json", rarityPermille: 20},
  {name: "Sunset", animationType: "lottie", animationUrl: BASE_MODEL + "Sunset.json", rarityPermille: 20},
  {name: "Toading...", animationType: "lottie", animationUrl: BASE_MODEL + "Toading....json", rarityPermille: 20},
  {name: "Tropical", animationType: "lottie", animationUrl: BASE_MODEL + "Tropical.json", rarityPermille: 20},
  {name: "Two Face", animationType: "lottie", animationUrl: BASE_MODEL + "Two%20Face.json", rarityPermille: 20},
  {name: "X-Ray", animationType: "lottie", animationUrl: BASE_MODEL + "X-Ray.json", rarityPermille: 20},
  {name: "Yellow Hug", animationType: "lottie", animationUrl: BASE_MODEL + "Yellow%20Hug.json", rarityPermille: 20},
  {name: "Yellow Purp", animationType: "lottie", animationUrl: BASE_MODEL + "Yellow%20Purp.json", rarityPermille: 20},
];